### ISSUE TITLE
Speak to the Server thru the NodeMCU

### ISSUE THREAD

**Issue by Leopardi628** [FNLHub/NodeMCU-FanProject#4] opened 2019-02-09 06:14 UTC
Data is being sent, but the signature (or confirmation) is not being received/confirmed by the NodeMCU.

**Comment by AhsenBaig** [comment] 2019-03-05 18:19
If the issue is marked as Done we should also close out the ticket with any additional information.

**Comment by knnth3** [comment] 2019-03-05 19:02
The connection on the nodeMCU now properly asks for the Auth header key. This allows for the software compare it and determine if connection comes from our server.

**Closed as completed by knnth3** 2019-03-05 19:02 UTC
Labels: bug
