### ISSUE TITLE
Add pick up lines for the NodeMCU and Server

### ISSUE THREAD

**Issue by Leopardi628** [FNLHub/NodeMCU-FanProject#2] opened 2019-02-09 04:31 UTC
We need a pick up line that will strengthen the connection between the NodeMCU and the server it is trying to connect with. Any suggestions are welcome. Potential pick-up lines will be polished if necessary.

**Comment by adelgadoo** [comment] 2019-02-09 04:38
Is your name Wi-Fi? Because I'm feeling a connection.

I'm not staring, I'm just stuck in a loop.

You are my loop condition. I keep coming back to you.

**Comment by AhsenBaig** [comment] 2019-03-05 18:20
If the issue is marked as Done we should also close out the ticket with any additional information.

**Comment by knnth3** [comment] 2019-03-05 18:58
The given options were evaluated, and with extreme thought the winner goes to #1!

“Is your name WiFi? Because I’m feeling a connection .”

**Closed as completed by knnth3** 2019-03-05 18:58 UTC
Labels: enhancement
